#!/bin/sh
# chkconfig: 2345 99 00

case "$1" in
'start')
	/usr/local/instalacion/apache-tomcat-7.0.42/bin/startup.sh
	touch /var/lock/subsys/tomcat
	;;
'stop')
	/usr/local/instalacion/apache-tomcat-7.0.42/bin/shutdown.sh
	rm -f /var/lock/subsys/tomcat
	;;
*)
	echo "Usage: $0 { start | stop }"
	;;
esac
exit 0
